name: pxt-testghpkgs

on:
  schedule:
    - cron:  '0 0 * * 6'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: |
          sudo npm install -g pxt
          npm install
      - name: pxt buildtarget
        run: pxt buildtarget
      - name: cache build output
        uses: actions/cache@v1
        env:
          cache-name: cache-testghpkgs
        with:
          path: temp/ghpkgs
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-       
      - name: pxt testghpkgs
        run: pxt testghpkgs
        env:
          PXT_FORCE_GITHUB_PROXY: 1
          PXT_ACCESS_TOKEN: ${{ secrets.PXT_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.TRAVIS_GITHUB_ACCESS_TOKEN }}
      - name: upload build log
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: logs
          path: temp/ghpkgs/*.txt
